version: '3.8'

name: einsatzplan

## use 'docker-compose up mongo' to only start the actual db
## use 'docker-compose up mongo_seed' to only start the seed data service
## use 'docker-compose up' to start both

services:
  mongo:
    build:
      context: ./mongodb_replica
      args:
        MONGO_VERSION: latest
    env_file:
      - ./database.dev.env
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27019',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20

  # seed data
  mongo_seed:
    build:
      context: ./mongodb_seed
      args:
        MONGO_VERSION: latest
    depends_on:
      - mongo
    ports:
      - '27018:27018'
    restart: on-failure
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 20s

volumes:
  mongodb_data:
